version: '3'

services:
  php-fpm:
    build: php-fpm
    ports:
      - 9000:9000
    volumes:
      - ./app:/var/www/html/app
    restart: always
    environment:
      APP_ENV:
      APP_DEBUG:
      APP_KEY:
      APP_TIMEZONE:
      LOG_CHANNEL:
      LOG_SLACK_WEBHOOK_URL:
      DB_CONNECTION:
      DB_HOST:
      DB_PORT: 
      DB_DATABASE:
      DB_USERNAME:
      DB_PASSWORD:
      CACHE_DRIVER:
      QUEUE_DRIVER:      
    networks:
      - backend
    links:
      - db


  nginx:
    build: nginx
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www/html/app
    restart: always       
    links:
      - php-fpm
    networks:
      - backend


  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD:
    networks:
      - backend


volumes:
  db_data:
#  app_data: ./app

networks:
  backend:
    driver: bridge
 
